spring:
  profiles:
    active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: info
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chenxin520
    max-wait: 60000
    max-active: 100
    min-idle: 10
    initial-size: 10

mybatis:
  mapperLocations: classpath:mapper/*.xml

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: 95d53510-65d8-40a3-bfa2-ba3bc6259a10
      group: SEATA_GROUP
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: 95d53510-65d8-40a3-bfa2-ba3bc6259a10
      group: SEATA_GROUP
      username: nacos
      password: nacos

  service:
    vgroup-mapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false